# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_url', models.CharField(max_length=200)),
                ('linkedIn_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor', models.CharField(max_length=200)),
                ('funding_round', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=100)),
                ('funding_date', models.DateField(verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('apply_post', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invested_in', models.CharField(max_length=100)),
                ('invested_amount', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=500)),
                ('pub_date', models.DateField(verbose_name='date')),
                ('img_link', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.News')),
            ],
        ),
        migrations.CreateModel(
            name='StartupContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('linkedIn', models.CharField(max_length=200)),
                ('facebook', models.CharField(max_length=200)),
                ('twitter', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StartupName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=200)),
                ('found_date', models.DateField(verbose_name='date')),
                ('link', models.CharField(max_length=200)),
                ('logo_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='startupcontact',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.StartupName'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.StartupName'),
        ),
        migrations.AddField(
            model_name='invested',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.StartupName'),
        ),
        migrations.AddField(
            model_name='internship',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.StartupName'),
        ),
        migrations.AddField(
            model_name='funding',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.StartupName'),
        ),
        migrations.AddField(
            model_name='founder',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.StartupName'),
        ),
    ]
