# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0004_auto_20160902_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='invested',
            name='invedted_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date'),
            preserve_default=False,
        ),
    ]
