# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0005_invested_invedted_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invested',
            old_name='invedted_date',
            new_name='invested_date',
        ),
    ]
