# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0006_auto_20161105_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invested',
            name='invested_in',
            field=models.CharField(max_length=1000),
        ),
    ]
