# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0008_auto_20161105_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invested',
            name='invested_amount',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='invested',
            name='invested_date',
            field=models.CharField(max_length=1000),
        ),
    ]
