# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-06 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0010_auto_20161106_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='funding_date',
            field=models.CharField(max_length=1000),
        ),
    ]
